{
 "title": "Montioring-DashBoard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Requests Count Over Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(requests_total[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(requests_total[1m])) by (endpoint)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (50th Percentile / Median)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_latency_seconds_bucket[5m])) by (le, endpoint))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP requests grouped by endpoint",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (95th Percentile)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket[5m])) by (le, endpoint))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of HTTP requests per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "expr": "requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Request Latency (in seconds)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(request_latency_seconds_sum[1m])\r\n/\r\nrate(request_latency_seconds_count[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}