# traffic-simulator-setup.yml

- name: Setup Traffic Simulator
  hosts: localhost
  vars:
  - network_name: microservice_monitoring_stack
  tasks:
    - name: Check if Docker network already exists
      shell: docker network ls --format '{{ "{{.Name}}" }}' | grep -w {{ network_name }}
      register: network_exists
      ignore_errors: yes

    - name: Create Docker network
      shell: docker network create {{ network_name }} --driver=bridge
      when: network_exists.rc != 0

    # - name: Create Docker network 
    #   shell: >
    #     docker network create {{ network_name }} --driver=bridge
    #   ignore_errors: yes

    - name: Build Traffic Simulator image
      shell:  
        docker build -t traffic-simulator:v1 {{ playbook_dir }}/../traffic-simulator

    - name: Run the Traffic Simulator
      shell: >
        docker run -d --name traffic-simulator --network {{ network_name }} traffic-simulator:v1
